deployments:
  deploymentGating:
    enabled: true 
    retry: 50 
    sleep: 30 
    environments: 
    - Development
    - Production
    - Prod
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2UzZWQxNjU3LTY2NmMtNDE3Mi1iODM0LTZlYjFkZmM4NTEzMS8zMjdlYTZjOC1iMTc0LTExZWYtOGJmMC0xMjAxZjE2ZWQ0MWY=
